# Generated by Django 3.2.5 on 2022-10-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppRenoTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproject',
            old_name='workDone',
            new_name='work_Being_Done',
        ),
        migrations.AddField(
            model_name='newproject',
            name='afterPhoto1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='afterPhoto2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='afterPhoto3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='afterPhoto4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='beforePhoto1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='beforePhoto2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='beforePhoto3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='beforePhoto4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
