# Generated by Django 3.2.5 on 2022-10-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppRenoTracker', '0002_auto_20220930_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='project_tag',
            field=models.CharField(default='No Tag', max_length=255),
        ),
    ]
