# Generated by Django 3.2.5 on 2022-10-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppRenoTracker', '0003_newproject_project_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproject',
            old_name='title',
            new_name='project_title',
        ),
        migrations.RemoveField(
            model_name='newproject',
            name='project_tag',
        ),
    ]
