# Generated by Django 3.2.5 on 2022-10-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppRenoTracker', '0005_auto_20221001_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproject',
            old_name='houseLevel',
            new_name='house_Level',
        ),
    ]
