# Generated by Django 3.2.5 on 2022-10-02 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppRenoTracker', '0006_rename_houselevel_newproject_house_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='project_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
