# Generated by Django 3.2.5 on 2022-10-02 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppRenoTracker', '0007_newproject_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='project_completion_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
