# Generated by Django 3.2.5 on 2022-10-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAppRenoTracker', '0008_newproject_project_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproject',
            name='project_completion_date',
            field=models.DateField(null=True),
        ),
    ]
